services:
  books:
    image: nginx:alpine
    mem_limit: 50m
    restart: unless-stopped
    ports:
      - "8200:80"
    volumes:
      - "/mnt/backup/books:/usr/share/nginx/html:ro"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
  logs:
    image: nginx:alpine
    restart: unless-stopped
    mem_limit: 50m
    ports:
      - "8100:80"
    volumes:
      - "/mnt/backup/logs:/usr/share/nginx/html:ro"
      - "./nginx-restricted.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./.htpasswd:/etc/nginx/.htpasswd:ro"
